### ISSUE TITLE
CSS is clean and succinct

### ISSUE THREAD

**Issue by ad3429** [ImperialZenta/prj-rev-bwfs-tea-cozy#3]
https://github.com/ImperialZenta/prj-rev-bwfs-tea-cozy/blob/master/teacozy/resources/css/style.css#L14-L155

Your CSS is short, clean and succinct -- good job! Your styling also matches the styling of the specification, so you did an excellent job of following these directions. Keep it up!

**Comment by ImperialZenta** [comment]
Thank you.
